verify openai api key

diff --git a/.github/workflows/end_to_end_create_infra_v2.1.yml b/.github/workflows/end_to_end_create_infra_v2.1.yml
--- a/.github/workflows/end_to_end_create_infra_v2.1.yml
+++ b/.github/workflows/end_to_end_create_infra_v2.1.yml
@@ -94,4 +94,15 @@ jobs:
       - name: Publish Deployment Summary
         run: |
           cat summary.md >> $GITHUB_STEP_SUMMARY
+
+      - name: Verify OpenAI Secret
+        run: |
+         if [ -z "$OPENAI_API_KEY" ]; then
+         echo "❌ Secret not found"
+         exit 1
+         else
+         echo "✅ OpenAI Secret Found"
+         fi
+         env:
+         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
              
